# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 57, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 0, 91, 61))
        self.label.setStyleSheet("color:white;\n"
"font-family:calibri;\n"
"font-size:26px;\n"
"font-weight:bold;")
        self.label.setObjectName("label")
        self.fullnamelabel = QtWidgets.QLabel(self.centralwidget)
        self.fullnamelabel.setGeometry(QtCore.QRect(40, 70, 111, 61))
        self.fullnamelabel.setStyleSheet("color:white;\n"
"font-family:calibri;\n"
"font-size:22px;\n"
"font-weight:bold;")
        self.fullnamelabel.setObjectName("fullnamelabel")
        self.fullnamefield = QtWidgets.QLineEdit(self.centralwidget)
        self.fullnamefield.setGeometry(QtCore.QRect(180, 90, 351, 31))
        self.fullnamefield.setObjectName("fullnamefield")
        self.emaillabel = QtWidgets.QLabel(self.centralwidget)
        self.emaillabel.setGeometry(QtCore.QRect(40, 130, 111, 61))
        self.emaillabel.setStyleSheet("color:white;\n"
"font-family:calibri;\n"
"font-size:22px;\n"
"font-weight:bold;")
        self.emaillabel.setObjectName("emaillabel")
        self.emailfield = QtWidgets.QLineEdit(self.centralwidget)
        self.emailfield.setGeometry(QtCore.QRect(180, 150, 351, 31))
        self.emailfield.setObjectName("emailfield")
        self.phonenolabel = QtWidgets.QLabel(self.centralwidget)
        self.phonenolabel.setGeometry(QtCore.QRect(40, 190, 111, 61))
        self.phonenolabel.setStyleSheet("color:white;\n"
"font-family:calibri;\n"
"font-size:22px;\n"
"font-weight:bold;")
        self.phonenolabel.setObjectName("phonenolabel")
        self.phonenofield = QtWidgets.QLineEdit(self.centralwidget)
        self.phonenofield.setGeometry(QtCore.QRect(180, 210, 351, 31))
        self.phonenofield.setObjectName("phonenofield")
        self.passwordfield = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordfield.setGeometry(QtCore.QRect(180, 280, 351, 31))
        self.passwordfield.setObjectName("passwordfield")
        self.passwordlabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordlabel.setGeometry(QtCore.QRect(40, 270, 111, 61))
        self.passwordlabel.setStyleSheet("color:white;\n"
"font-family:calibri;\n"
"font-size:22px;\n"
"font-weight:bold;")
        self.passwordlabel.setObjectName("passwordlabel")
        self.signupbutton = QtWidgets.QPushButton(self.centralwidget)
        self.signupbutton.setGeometry(QtCore.QRect(180, 340, 351, 41))
        self.signupbutton.setStyleSheet("background-color:orange;\n"
"font-style:calibri;\n"
"font-size:22px;\n"
"font-weight:bold;\n"
"color:white;\n"
"")
        self.signupbutton.setObjectName("signupbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sign Up window"))
        self.label.setText(_translate("MainWindow", "Sign Up"))
        self.fullnamelabel.setText(_translate("MainWindow", "Full Name:"))
        self.emaillabel.setText(_translate("MainWindow", "Email:"))
        self.phonenolabel.setText(_translate("MainWindow", "Phone no:"))
        self.passwordlabel.setText(_translate("MainWindow", "Password:"))
        self.signupbutton.setText(_translate("MainWindow", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
